version: '3'

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs:latest
    container_name: shardeum-bot
    restart: unless-stopped
    env_file: .env
    ports:
      - "3000:3000"
    volumes:
      - .:/home/shardeum-bot/app
    command: pm2 start npm --name "shardeum-bot" -- start