version: "3"

services:
  shardeum-bot:
    container_name: shardeum-bot
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/home/bot
    restart: 'always'
    env_file: .env
    ports:
      - '3000:3000'

